// slovnik-data.js
// Kompletní slovník energetických pojmů pro EDC

window.TERMS = [
    { letter: 'a', term: 'A', full: 'Ampér', text: 'Základní jednotka elektrického proudu v soustavě SI.' },
    { letter: 'a', term: 'AC', full: 'Střídavý proud', text: 'Směr proudu se periodicky mění (klasická zásuvka, kterou máme doma).' },
    { letter: 'a', term: 'Agregátor', full: '', text: 'Subjekt, který sdružuje flexibilitu od více výrobců nebo spotřebitelů a nabízí ji na trzích s elektřinou nebo SVR.' },
    { letter: 'a', term: 'Agrofotovoltaika', full: '', text: 'Kombinace zemědělství a výroby solární energie na stejném pozemku (panely jsou umístěny nad plodinami).' },
    { letter: 'a', term: 'Aktivní zákazník', full: '', text: 'Zákazník, který vyrábí elektřinu pro vlastní spotřebu a může sdílet přebytky v rámci skupiny sdílení (Lex OZE II).' },
    { letter: 'a', term: 'Akumulace', full: '', text: 'Ukládání elektřiny do zařízení (např. baterií) pro pozdější využití; zavedeno novelou Lex OZE III pro stabilizaci sítě a integraci OZE.' },
    { letter: 'a', term: 'Alokační klíč', full: '', text: 'Pravidlo rozdělení vyrobené elektřiny mezi odběrná místa ve skupině sdílení; může být statický, dynamický nebo hybridní (zaváděno průběžně v Lex OZE II a Lex OZE III).' },
    { letter: 'b', term: 'Baseline', full: '', text: 'Referenční (předpokládaná) spotřeba nebo výroba, sloužící k výpočtu poskytnuté flexibility při agregaci.' },
    { letter: 'b', term: 'Baterie (akumulátor)', full: '', text: 'Zařízení pro uchovávání elektrické energie v chemické formě.' },
    { letter: 'b', term: 'BOT', full: 'Banka Operátora trhu', text: 'Banka Operátora trhu' },
    { letter: 'b', term: 'BSD', full: 'Bezpečnostní standard dodávek', text: 'Bezpečnostní standard dodávek' },
    { letter: 'b', term: 'Biomasa', full: '', text: 'Souhrn látek tvořících těla všech organismů (rostlin i živočichů). V energetice se využívá ke spalování nebo k výrobě plynu.' },
    { letter: 'b', term: 'Bioplyn', full: '', text: 'Plyn vznikající anaerobní fermentací biomasy, využívaný jako obnovitelný zdroj energie.' },
    { letter: 'b', term: 'Biometan', full: '', text: 'Čištěný bioplyn s kvalitou zemního plynu, vhodný pro injektáž do sítě nebo jako palivo.' },
    { letter: 'b', term: 'B2B/B2C trh', full: '', text: 'Obchodní modely pro prodej energií (Business-to-Business pro firmy, Business-to-Consumer pro domácnosti).' },
    { letter: 'c', term: 'CC ČNB', full: 'Clearingové centrum České národní banky', text: 'Clearingové centrum České národní banky' },
    { letter: 'c', term: 'CDS', full: 'Centrum datových služeb Operátora trhu', text: 'Centrum datových služeb Operátora trhu' },
    { letter: 'c', term: 'Clearing', full: '', text: 'Vypořádání rozdílu Operátorem trhu mezi spotřebou elektřiny v regionech TDD určenou odečtem v OPM konečných zákazníků, kteří změnili dodavatele, a spotřebou elektřiny určenou pomocí metody TDD.' },
    { letter: 'c', term: 'CO', full: 'Oxid uhelnatý', text: 'Vysoce toxický a nebezpečný plyn bez chuti a zápachu vznikající při nedokonalém spalování (do ohniště nebo hořáku proudí málo kyslíku).' },
    { letter: 'c', term: 'CO2', full: 'Oxid uhličitý', text: 'Plyn bez chuti a zápachu, nejedovatý, při jeho větším množství hrozí udušení.' },
    { letter: 'c', term: 'CS OTE', full: 'Centrální informační systém Operátora trhu', text: 'Centrální informační systém Operátora trhu' },
    { letter: 'c', term: 'cos φ', full: 'Účiník', text: 'Bezrozměrná veličina vyjadřující poměr činného a zdánlivého výkonu.' },
    { letter: 'č', term: 'ČEPS, a.s.', full: 'České energetické přenosové soustavy, a.s.', text: 'Společnost ČEPS, a.s., státní akciová společnost, která vlastní a provozuje přenosovou soustavu v ČR.' },
    { letter: 'č', term: 'ČR', full: 'Česká republika', text: 'Česká republika' },
    { letter: 'd', term: 'Den D', full: '', text: 'Den dodávky, resp. den realizace uzavřených kontraktů na dodávku elektřiny.' },
    { letter: 'd', term: 'Dispečink', full: '', text: 'Řídící centrum, které v reálném čase sleduje a ovládá toky energie v síti, aby zajistilo rovnováhu mezi výrobou a spotřebou.' },
    { letter: 'd', term: 'Distribuční soustava', full: '', text: 'Sítě jednotlivých distributorů (ČEZdi, EG.D a PREdi) na hladině NN a VN.' },
    { letter: 'd', term: 'DC', full: 'Stejnosměrný proud', text: 'Proud teče stále jedním směrem (baterie).' },
    { letter: 'd', term: 'DB', full: 'Databáze', text: 'Databáze obecně' },
    { letter: 'd', term: 'Decentralizace', full: '', text: 'Přechod od velkých elektráren k většímu počtu malých zdrojů energie.' },
    { letter: 'd', term: 'DPH', full: 'Daň z přidané hodnoty', text: 'Daň z přidané hodnoty (DPH) je nepřímá daň, kterou platí koncový spotřebitel v ceně nakupovaného zboží nebo služeb, zatímco registrovaní podnikatelé ji v průběhu výroby a prodeje odvádějí státu pouze z hodnoty, o kterou produkt v daném kroku sami zhodnotili.' },
    { letter: 'd', term: 'DS', full: 'Distribuční soustava', text: 'Distribuční soustava je rozsáhlý systém elektrických vedení, transformoven a rozvoden, který zajišťuje přenos elektrické energie od přenosové soustavy (nebo přímo od výrobců) ke koncovým odběratelům, jako jsou domácnosti a firmy.' },
    { letter: 'd', term: 'DT', full: 'Denní trh s elektřinou', text: 'Denní trh s elektřinou je krátkodobý trh, na kterém se obchoduje elektřina na následující den v jednotlivých hodinových nebo blokových produktech.' },
    { letter: 'd', term: 'DÚF', full: 'Doplňující údaje pro fakturaci', text: 'Doplňující údaje pro fakturaci (DÚF) jsou specifické technické parametry a identifikační kódy (jako například EAN nebo EIC), které slouží distributorům a dodavatelům energií k přesnému určení odběrného místa a správnému výpočtu plateb za distribuci a související služby na vaší faktuře.' },
    { letter: 'd', term: 'Dynamický alokační klíč', full: '', text: 'Typ alokačního klíče, který rozděluje vyrobenou elektřinu podle aktuální spotřeby odběrných míst pro maximální využití (z Lex OZE II).' },
    { letter: 'd', term: 'Dynamická cena', full: '', text: 'Cena elektřiny, která se mění každou hodinu podle aktuálního vývoje na energetické burze' },
    { letter: 'e', term: 'EAN', full: 'European Article Number', text: 'Zkratka EAN označuje mezinárodní systém kódování a identifikace zboží, služeb a organizací; v energetice se používá jako unikátní identifikátor odběrného místa.' },
    { letter: 'e', term: 'EANd', full: 'EAN for delivery', text: 'EANd je registrační číslo předávacího místa, které patří výrobně elektřiny (např. fotovoltaické elektrárně) a ze kterého se elektřina sdílí či odesílá do sítě nebo skupiny sdílení. Je to unikátní 18místný kód, přidělený provozovatelem distribuční soustavy.' },
    { letter: 'e', term: 'EANo', full: 'EAN for off-take', text: 'EANo je registrační číslo odběrného místa, tedy místa, kde elektřinu sdílení přijímá spotřebitel (např. váš dům či byt).' },
    { letter: 'e', term: 'EDC', full: 'Elektroenergetické datové centrum', text: 'Elektroenergetické datové centrum; společnost zajišťující sběr dat v energetice, jejich standardizaci a sdílení.' },
    { letter: 'e', term: 'EIC', full: 'Energy Identification Code', text: 'Zkratka pro Energy Identification Code, 16místný kód, který slouží k identifikaci odběrného místa plynu.' },
    { letter: 'e', term: 'Elektřina', full: '', text: 'Tok elektronů vodičem. V energetice ji dělíme na mnoho forem - tepelnou, elektrickou, chemickou, jadernou nebo např. kinetickou.' },
    { letter: 'e', term: 'Elektroměr', full: '', text: 'Přístroj určený k měření množství elektřiny, která byla dodaná nebo odebraná ze sítě.' },
    { letter: 'e', term: 'Elektromobilita', full: '', text: 'Obor zabývající se vozidly s elektrickým pohonem, která čerpají energii nejčastěji z obnovitelných zdrojů.' },
    { letter: 'e', term: 'Emisní povolenka', full: '', text: 'Certifikát, který opravňuje majitele vypustit do atmosféry jednu tunu oxidu uhličitého. Je to nástroj k regulaci znečištění.' },
    { letter: 'e', term: 'Energetická náročnost', full: '', text: 'Množství energie potřebné k výrobě určitého produktu nebo k provozu budovy. Cílem moderní energetiky je tuto náročnost snižovat.' },
    { letter: 'e', term: 'Energetické společenství', full: '', text: 'Právnická osoba umožňující sdílení elektřiny mezi členy (až 1000 odběrných míst), založená podle Lex OZE II' },
    { letter: 'e', term: 'ERÚ', full: 'Energetický regulační úřad', text: 'Energetický regulační úřad (ERÚ) je nezávislý státní orgán, který v Česku reguluje ceny v monopolních oblastech energetiky (např. platby za distribuci), uděluje licence k podnikání, dohlíží na férovou hospodářskou soutěž a chrání zájmy spotřebitelů v odvětví elektřiny, plynu a tepla.' },
    { letter: 'e', term: 'ES ČR', full: 'Elektrizační soustava České republiky', text: 'Elektrizační soustava České republiky je vzájemně propojený, centrálně řízený soubor zařízení pro výrobu, přenos, transformaci a distribuci elektřiny (včetně systémů měření a regulace), který zajišťuje spolehlivé dodávky energie od elektráren až ke koncovým spotřebitelům v rámci celé země i v napojení na zahraniční sítě.' },
    { letter: 'e', term: 'EU', full: 'Evropská unie', text: 'Evropská unie je unikátní politické a hospodářské společenství 27 evropských států, které sdílejí část své suverenity společným orgánům, aby společně zajišťovaly mír, stabilitu a fungování jednotného vnitřního trhu založeného na volném pohybu osob, zboží, služeb a kapitálu.' },
    { letter: 'e', term: 'EZ', full: 'Energetický zákon', text: 'Energetický zákon, zákon č. 458/2000 Sb., o podmínkách podnikání a výkonu státní správy v energetických odvětvích a o změně některých zákonů, ve znění pozdějších předpisů.' },
    { letter: 'f', term: 'F', full: 'Farad', text: 'Jednotka elektrické kapacity' },
    { letter: 'f', term: 'Fáze', full: '', text: 'V elektrotechnice označuje časový posun průběhu střídavého napětí nebo proudu. V běžné zásuvce máme jednu fáze, pro pohon silných motorů se používá třífázová zásuvka.' },
    { letter: 'f', term: 'Flexibilita', full: '', text: 'Schopnost cíleně měnit výrobu nebo spotřebu elektřiny v reakci na potřeby soustavy, často za úplatu; zavedeno Lex OZE III.' },
    { letter: 'f', term: 'FZ', full: 'Finanční zajištění', text: 'Finanční zajištění, poskytnuté Subjektem zúčtování Operátorovi trhu k pokrytí finančních závazků plynoucích z působení Subjektu zúčtování na trhu s elektřinou nebo plynem.' },
    { letter: 'f', term: 'FVE', full: 'Fotovoltaická elektrárna', text: 'Elektrárna využívající sluneční energii k výrobě elektřiny prostřednictvím fotovoltaických panelů.' },
    { letter: 'f', term: 'Fotovoltaický článek', full: '', text: 'Základní konstrukční prvek solárního panelu, nejčastěji vyráběný z křemíku.' },
    { letter: 'f', term: 'Foton', full: '', text: 'Částice světla, která při dopadu na fotovoltaický panel předává svoji energii elektronům, čímž vzniká elektrický proud.' },
    { letter: 'f', term: 'Fosilní paliva', full: '', text: 'Neobnovitelné zdroje energie vzniklé v dávné geologické minulosti z odumřelých organismů (ropa, zemní plyn, uhlí).' },
    { letter: 'f', term: 'Frekvence', full: '', text: 'Počet kmitů střídavého proudu za sekundu. V evropské síti je standardní frekvence 50 Hz a její stabilita je klíčová pro bezpečnost sítě.' },
    { letter: 'g', term: 'Gama záření', full: '', text: 'Vysoce energetické elektromagnetické záření s velmi krátkou vlnovou délkou. Je nejpronikavějším druhem radioaktivního záření a vyžaduje silné stínění (olovo nebo beton).' },
    { letter: 'g', term: 'Generátor', full: '', text: 'Stroj, který přeměňuje mechanickou energii (např. z turbíny) na energii elektrickou.' },
    { letter: 'g', term: 'Geotermální energie', full: '', text: 'Využití tepla zemského jádra pro výrobu páry nebo vytápění.' },
    { letter: 'g', term: 'Gigajoule', full: '', text: 'Jednotka energie, která se v Česku nejčastěji používá pro vyúčtování dodaného tepla z tepláren.' },
    { letter: 'g', term: 'Green Deal', full: 'Zelená dohoda', text: 'Zelená dohoda, je to soubor politických iniciativ Evropské komise, jejichž hlavním cílem je dosáhnout do roku 2050 klimatické neutrality.' },
    { letter: 'g', term: 'Grid', full: 'Elektrická síť', text: 'Elektrická síť, je to anglický výraz pro přenosovou a distribuční soustavu. Dnes se často mluví o Smart grids (chytrých sítích), které dokážou samy regulovat spotřebu a výrobu.' },
    { letter: 'g', term: 'GWh', full: 'Gigawatthodina', text: 'Jednotka velmi velkého množství energie, 1 GWh = 1 000 MWh' },
    { letter: 'h', term: 'HTTPS', full: 'Hypertext Transfer Protocol Secure', text: 'Zabezpečený internetový protokol' },
    { letter: 'h', term: 'HDS', full: 'Hlavní domovní skříň', text: 'Místo, kde se objekt napojuje na distribuční síť, obsahuje hlavní (zpravidla už nožové) pojistky. Někdy též nazývána jako přípojková skříň.' },
    { letter: 'h', term: 'HDO', full: 'Hromadné dálkové ovládání', text: 'Systém, kterým distributor pomocí signálů posílaných po síti časově ovládá zapínání a vypínání spotřebičů s velkým odběrem (bojlery, akumulační kamna...) a tím pádem přepíná mezi vysokým a nízkým tarifem.' },
    { letter: 'h', term: 'HJ', full: 'Hlavní jistič', text: 'Ochranný prvek omezující maximální množství proudu, které může odběrné místo spotřebovat. Je součást paušálního poplatku za elektřinu.' },
    { letter: 'h', term: 'HW', full: 'Hardware', text: 'Hardware, počítačové zařízení a periferie' },
    { letter: 'h', term: 'Hz', full: 'Hertz', text: 'Jednotka frekvence, počet period za sekundu; v síti obvykle 50 Hz' },
    { letter: 'h', term: 'Hydroelektrárna', full: '', text: 'Vodní elektrárna využívající energii tekoucí nebo padající vody k roztočení turbíny.' },
    { letter: 'h', term: 'H', full: 'Henry', text: 'Jednotka elektrické indukčnosti' },
    { letter: 'ch', term: 'Chladicí věž', full: '', text: 'Dominanta velkých elektráren sloužící k ochlazování oteplené vody z kondenzátoru pomocí proudícího vzduchu. To, co z nich vidíme stoupat, je čistá vodní pára.' },
    { letter: 'ch', term: 'Chladicí okruh', full: '', text: 'Uzavřený nebo otevřený systém potrubí, čerpadel a výměníků, kterým protéká médium odvádějící odpadní teplo z procesu - např. z jaderného reaktoru nebo spalovacího motoru.' },
    { letter: 'ch', term: 'Chladivo reaktoru', full: '', text: 'Médium (voda, plyn, tekutý kov) protékající aktivní zónou jaderného reaktoru, odebírá teplo vznikající štěpením a přenáší ho k výrobě páry.' },
    { letter: 'ch', term: 'Chránič', full: '', text: 'Proudový chránič je velmi citlivý bezpečnostní prvek v elektroinstalaci, který odpojí obvod, pokud zjistí, že proud uniká mimo daný obvod - např. přes tělo člověka do země.' },
    { letter: 'ch', term: 'Charakteristika', full: '', text: 'Zatěžovací charakteristika - závislost napětí nebo výkonu zdroje na velikosti odebíraného proudu. Je klíčová pro stabilitu sítě.' },
    { letter: 'i', term: 'IČO', full: 'Identifikační číslo organizace', text: 'Identifikační číslo organizace' },
    { letter: 'i', term: 'Impedance', full: '', text: 'Celkový zdánlivý odpor elektrického obvodu proti průtoku střídavého proudu. Skládá se z resistance (odporu) a reaktance (indukční a kapacitní složky).' },
    { letter: 'i', term: 'Indukce', full: '', text: 'Jev, při kterém v měnícím se magnetickém poli vzniká ve vodiči elektrické napětí. Na tomto principu fungují všechny generátory a transformátory.' },
    { letter: 'i', term: 'IDA', full: 'Intraday aukce', text: 'Vnitrodenní aukce, součást vnitrodenního obchodování s elektřinou.' },
    { letter: 'i', term: 'Invertor', full: '', text: 'Jiným slovem střídač, je to klíčové zařízení ve fotovoltaických elektrárnách měnící stejnosměrný proud (DC) na střídavý proud (AC) o frekvenci 50 Hz pro domácí spotřebiče nebo síť.' },
    { letter: 'i', term: 'IV', full: 'Instalovaný výkon', text: 'Součet jmenovitých výkonů všech energetických zdrojů (např. všech fotovoltaických panelů nebo generátorů v elektrárně) v daném systému. Udává se zpravidla v kWp = Kilo-Watt-peak.' },
    { letter: 'i', term: 'ID', full: 'Identifikátor', text: 'Identifikátor obecně' },
    { letter: 'i', term: 'IS', full: 'Informační systém', text: 'Informační systém obecně' },
    { letter: 'i', term: 'Inteligentní měření', full: 'Smart metering', text: 'Jinými slovy Smart metering = moderní elektroměry, které umožňují dálkový odečet v jednotlivých čtvrthodinových intervalech, dokáží sledovat spotřebu i výrobu v reálném čase.' },
    { letter: 'i', term: 'ISO 27001', full: 'Mezinárodní standard řízení bezpečnosti informací', text: 'Mezinárodní standard upravující systém řízení bezpečnosti informací.' },
    { letter: 'j', term: 'J, MJ, GJ, TJ', full: 'Joule, Megajoule, Gigajoule, Terajoule', text: 'Jednotka práce (energie) 1 TJ = 10¹² J 1 TJ = 10³ GJ 1 TJ = 10⁶ MJ 1 J = 1 Ws' },
    { letter: 'j', term: 'Jádro', full: '', text: 'Atomové jádro je centrální část atomu složená z protonů a neutronů. V energetice využíváme energii, která drží tyto částice pohromadě a štěpíme je.' },
    { letter: 'j', term: 'Jaderná elektrárna', full: '', text: 'Je zařízení, které vyrábí elektřinu pomocí tepla uvolněného při řízené řetězové štěpné reakci v reaktoru.' },
    { letter: 'j', term: 'Jaderné palivo', full: '', text: 'Materiál (nejčastěji uran, konkrétně ve formě oxidu uraničitého v tabletách), který je vložen do reaktoru za účelem výroby energie.' },
    { letter: 'j', term: 'Jaderný dozor', full: 'Státní úřad pro jadernou bezpečnost', text: 'Státní úřad pro jadernou bezpečnost je orgán, který v Česku dohlíží na provoz jaderných zařízení.' },
    { letter: 'j', term: 'Jalový výkon', full: '', text: 'Jalový výkon je výkon, který se v elektrických obvodech střídavého proudu přelévá mezi zdrojem a spotřebičem, ale nekoná užitečnou práci. Zatěžuje však vedení a stroje.' },
    { letter: 'j', term: 'Jednofázová soustava', full: '', text: 'Systém střídavého proudu využívající dva vodiče (fázový a nulový). Běžně se používá pro méně náročné spotřebiče v domácnostech.' },
    { letter: 'j', term: 'Jednotková cena', full: '', text: 'Cena za jednu kilowatthodinu (kWh) nebo megawatthodinu (MWh) energie, která se skládá z obchodní a distribuční části.' },
    { letter: 'j', term: 'Jistič', full: '', text: 'Automatický vypínač, který přeruší elektrický obvod, pokud jím začne téct příliš velký proud (při přetížení nebo zkratu). Chrání vedení před požárem a zničením.' },
    { letter: 'j', term: 'Jmenovité napětí', full: '', text: 'Hodnota napětí, pro kterou je dané zařízení nebo síť konstruována a pojmenována, např. 230 V v zásuvce.' },
    { letter: 'k', term: 'Kabel', full: '', text: 'Izolovaný vodič nebo skupina vodičů sloužící k přenosu elektrické energie.' },
    { letter: 'k', term: 'Kazeta', full: 'Palivová kazeta', text: 'Soubor palivových proutků s jaderným palivem, který se jako jeden celek vkládá do reaktoru.' },
    { letter: 'k', term: 'Kogenerace', full: '', text: 'Společná výroba elektřiny a tepla. Místo toho, aby se teplo z výroby elektřiny vypustilo do ovzduší (jako u běžných elektráren), využije se k vytápění.' },
    { letter: 'k', term: 'Kondenzátor', full: '', text: 'V tepelné energetice je to výměník tepla, ve kterém se pára po průchodu turbínou mění zpět na vodu. V elektrotechnice je to součástka schopná uchovat elektrický náboj v elektrickém poli.' },
    { letter: 'k', term: 'Konečný zákazník, KZ', full: '', text: 'Odběratel, který používá dodanou energii pouze pro svoji spotřebu, nikoliv pro další prodej' },
    { letter: 'k', term: 'kV', full: 'Kilovolt', text: 'Jednotka vyššího elektrického napětí, 1 kV = 1 000 V' },
    { letter: 'k', term: 'kW', full: 'Kilowatt', text: 'Jednotka činného výkonu, 1 kW = 1 000 W' },
    { letter: 'k', term: 'kWh', full: 'Kilowatthodina', text: 'Běžná fakturační jednotka elektrické energie, 1 kWh = 1 000 Wh' },
    { letter: 'k', term: 'kVA', full: 'Kilovoltampér', text: 'Jednotka zdánlivého výkonu, 1 kVA = 1 000 VA' },
    { letter: 'k', term: 'kVAr', full: 'Kilovoltampér reaktanční', text: 'Jednotka jalového výkonu, 1 kVAr = 1 000 VAr' },
    { letter: 'k', term: 'kA', full: 'Kiloampér', text: 'Jednotka velkého elektrického proudu, 1 kA = 1 000 A' },
    { letter: 'k', term: 'KVET', full: 'Kombinovaná výroba elektřiny a tepla', text: 'Kombinovaná výroba elektřiny a tepla (kogenerace), vysoce účinná výroba elektřiny a tepla v jednom procesu.' },
    { letter: 'l', term: 'LED', full: 'Light Emitting Diode', text: 'Je to polovodičová součástka, která přeměňuje elektrický proud přímo na světlo s vysokou účinností. Oproti klasickým žárovkám spotřebuje až o 90% méně energie.' },
    { letter: 'l', term: 'L1, L2, L3', full: '', text: 'Označení jednotlivých fází v třífázové elektrické soustavě. Na chytrých elektroměrech tyto fáze vidíme i na displeji.' },
    { letter: 'l', term: 'LEX OZE I', full: '', text: 'Hlavním cílem bylo odstranit byrokratické bariéry pro malé instalace. Do 50 kW (původně do 10 kW) již není potřeba licence. Dále posunulo stavby nad 1 MW do oblasti stavby ve veřejném zájmu, což urychluje povolovací procesy.' },
    { letter: 'l', term: 'LEX OZE II', full: '', text: 'Tato novela přinesla možnost sdílení elektřiny a vznik Elektroenergetického datového centra, které výměnu dat o sdílení eviduje a přepočítává.' },
    { letter: 'l', term: 'LEX OZE III', full: '', text: 'Hlavními tématy jsou akumulace, agregace a flexibilita. Nastanou jasná pravidla pro provoz velkých bateriových úložišť, bude možné sdružovat menší zdroje a nabízet jejich výkon nebo akumulaci ve chvíli, kdy to bude potřeba.' },
    { letter: 'l', term: 'LDS', full: 'Lokální distribuční soustava', text: 'Lokální distribuční soustava, distribuční síť nepřipojená k přenosové soustavě.' },
    { letter: 'l', term: 'Lumen', full: '', text: 'Jednotka světelného toku, která uvává, kolik světla celkem vyzáří světelný zdroj do všech směrů. Dnes je důležitějším údajem než watty.' },
    { letter: 'm', term: 'Magnetické pole', full: '', text: 'Silové pole vznikající kolem vodičů s proudem a v generátorech. Je nezbytné pro přeměnu mechanické energie na elektrickou.' },
    { letter: 'm', term: 'Meziokruh', full: '', text: 'Druhý uzavřený okruh v jaderné elektrárně (sekundární). Vyrábí se v něm pára pro turbínu a odděluje radioaktivní vodu z reaktoru od turbíny.' },
    { letter: 'm', term: 'Měřicí transformátor', full: '', text: 'Speciální zařízení, které snižuje vysoké napětí nebo proudy na úrovně, které jsou pro měřicí přístroje a elektroměry bezpečné.' },
    { letter: 'm', term: 'Mikrosíť', full: '', text: 'Lokální energetický systém (např. v rámci obce nebo areálu), který dokáže fungovat nezávisle na hlavní celostátní síti díky vlastním zdrojům a bateriím.' },
    { letter: 'm', term: 'Modul', full: 'Fotovoltaický modul', text: 'Fotovoltaický modul je odborný název pro solární panel, který se skládá z propojených solárních článků.' },
    { letter: 'm', term: 'Moderátor', full: '', text: 'V energetice je to látka, která zpomaluje rychlé neutrony vznikající při štěpení na tzv. tepelné neutrony, které snadněji vyvolají další štěpení. Nejčastěji se používá voda, těžká voda nebo grafit.' },
    { letter: 'm', term: 'MPO', full: 'Ministerstvo průmyslu a obchodu', text: 'Ministerstvo průmyslu a obchodu' },
    { letter: 'm', term: 'MV', full: 'Megavolt', text: 'Jednotka velmi vysokého elektrického napětí, 1 MV = 1 000 kV' },
    { letter: 'm', term: 'MW', full: 'Megawatt', text: 'Jednotka velkého činného výkonu, 1 MW = 1 000 kW' },
    { letter: 'm', term: 'MWh', full: 'Megawatthodina', text: 'Jednotka velkého množství energie, 1 MWh = 1 000 kWh' },
    { letter: 'm', term: 'MVA', full: 'Megavoltampér', text: 'Jednotka velkého zdánlivého výkonu, 1 MVA = 1 000 kVA' },
    { letter: 'm', term: 'MVAr', full: 'Megavoltampér reaktanční', text: 'Jednotka velkého jalového výkonu, 1 MVAr = 1 000 kVAr' },
    { letter: 'n', term: 'Napětí', full: '', text: 'Elektrické napětí je rozdíl elektrických potenciálů mezi dvěma body. Lze si ho představit jako tlak, který žene elektrony vodičem. Jednotkou je Volt (V).' },
    { letter: 'n', term: 'Neutron', full: '', text: 'Elektricky neutrální částice v jádře atomu. V energetice jsou klíčové tzv. tepelné neutrony, které způsobují štěpení jader uranu.' },
    { letter: 'n', term: 'Nízké napětí', full: '', text: 'V Česku se jedná o napětí do 1000V. Patří sem běžné rozvody v domácnostech (230 V a 400V).' },
    { letter: 'n', term: 'Nízký tarif', full: '', text: 'Časové pásmo rozložené do několika různě dlouhých časových úseků během každého dne. Cena elektřiny je během této doby nižší. Ovládá se systémem HDO a dříve se mu říkalo "noční proud".' },
    { letter: 'n', term: 'Nulový vodič', full: '', text: 'Pracovní vodič v elektrické síti, který slouží k uzavření obvodu. Má modrou barvu izolace.' },
    { letter: 'n', term: 'Nominální výkon', full: '', text: 'Jmenovitý výkon zařízení stanovený výrobcem pro trvalý provoz za standardních podmínek.' },
    { letter: 'n', term: 'NET4GAS, s.r.o.', full: 'NET4GAS, s.r.o.', text: 'Provozovatel přepravní soustavy plynu v České republice.' },
    { letter: 'n', term: 'NOx', full: 'Oxidy dusíku', text: 'Oxidy dusíku' },
    { letter: 'n', term: 'NPpS', full: 'Náklady na podpůrné služby', text: 'Průměrné hodinové hodnoty nákladů na aktivované PpS (regulační energie).' },
    { letter: 'o', term: 'Obchodník s elektřinou', full: '', text: 'Fyzická či právnická osoba, která je držitelem licence na obchod s elektřinou a nakupuje elektřinu za účelem jejího dalšího prodeje.' },
    { letter: 'o', term: 'Obchodník s plynem', full: '', text: 'Fyzická či právnická osoba, která je držitelem licence na obchod s plynem a nakupuje plyn za účelem jeho dalšího prodeje.' },
    { letter: 'o', term: 'Obchodní flexibilita', full: '', text: 'Schopnost účastníků trhu reagovat na změny cen, výroby a spotřeby. Přináší úsporu nákladů, stabilitu sítě a lepší integraci OZE.' },
    { letter: 'o', term: 'Odpor', full: '', text: 'Neboli rezistance je vlastnost materiálu bránit průtoku elektrického proudu. Při překonávání odporu vzniká teplo.' },
    { letter: 'o', term: 'Ochrana', full: '', text: 'Zařízení, která chrání síť a spotřebiče před účinky zkratů a přetížení (jističe, pojistky, relé...).' },
    { letter: 'o', term: 'Off-grid', full: '', text: 'Systém ostrovního provozu bez připojení k distribuční síti.' },
    { letter: 'o', term: 'OPE', full: 'Obchodní podmínky OTE pro elektroenergetiku', text: 'Obchodní podmínky OTE, a.s., pro elektroenergetiku; dostupné na webových stránkách OTE.' },
    { letter: 'o', term: 'OPM', full: 'Odběrné/předávací místo', text: 'Odběrné / předávací místo' },
    { letter: 'o', term: 'Ostrovní provoz', full: '', text: 'Režim, kdy budova nebo celá oblast funguje úplně nezávisle na veřejné distribuční síti a není k ní připojena, např. pomocí vlastních panelů a baterií.' },
    { letter: 'o', term: 'OPP', full: 'Obchodní podmínky OTE pro plynárenství', text: 'Obchodní podmínky OTE, a.s., pro plynárenství; dostupné na webových stránkách OTE.' },
    { letter: 'o', term: 'OTE, Operátor trhu', full: 'Operátor trhu s elektřinou a plynem, a.s.', text: 'Akciová společnost OTE, a.s., která působí na trhu s elektřinou v ČR od roku 2001 a na trhu s plynem od roku 2010, jejímž zakladatelem a jediným akcionářem je stát Česká republika. Výkon akcionářských práv provádí z pověření státu Ministerstvo průmyslu a obchodu.' },
    { letter: 'o', term: 'OZE', full: 'Obnovitelné zdroje energie', text: 'Obnovitelné zdroje energie; podle zákona o životním prostředí: přírodní zdroje, které mají schopnost se při postupném spotřebovávání částečně nebo úplně obnovovat, a to samy nebo za přispění člověka; podle zákona o podpoře využívání obnovitelných zdroj: energie větru, energie slunečního záření, geotermální energie, energie vody, energie půdy, energie vzduchu, energie biomasy, energie skládkového plynu, energie kalového plynu a energie bioplynu.' },
    { letter: 'o', term: 'Ω', full: 'Ohm', text: 'Jednotka elektrického odporu. Základní vztah elektrotechniky, který říká, že proud v obvodu je přímo úměrný napětí a nepřímo úměrný odporu (I = U / R).' },
    { letter: 'p', term: 'Palivový článek', full: '', text: 'Zařízení, které mění chemickou energie paliva přímo na elektřinu a teplo bez spalování.' },
    { letter: 'p', term: 'Palivový proutek', full: '', text: 'Kovová trubice naplněná tabletami oxidu uraničitého. Stovky takových proutků tvoří jednu palivovou kazetu.' },
    { letter: 'p', term: 'Paralelní zapojení', full: '', text: 'Zapojení součástek, např. FVE panelů, vedle sebe (rozbočení).' },
    { letter: 'p', term: 'Parogenerátor', full: '', text: 'Obří výměník tepla v jaderné elektrárně, kde horká voda z reaktoru ohřívá vodu v sekundárním okruhu a vyrábí páru pro turbínu.' },
    { letter: 'p', term: 'Proud', full: '', text: 'Usměrněný pohyb elektronů, jednotkou je Ampér (A).' },
    { letter: 'p', term: 'Potenciál', full: '', text: 'Schopnost elektrického pole konat práci. Rozdíl potenciálů mezi dvěma body je napětí.' },
    { letter: 'p', term: 'Primární okruh', full: '', text: 'Uzavřený okruh vody, která protéká přímo jaderným reaktorem, ohřívá se a v parogenerátoru předává teplo sekundárnímu okruhu.' },
    { letter: 'p', term: 'PC', full: 'Parametrická cena', text: 'Parametrická cena, vyjadřuje očekávanou jednotkovou ceny odchylky.' },
    { letter: 'p', term: 'PDS', full: 'Provozovatel distribuční soustavy', text: 'Provozovatel distribuční soustavy' },
    { letter: 'p', term: 'PLDS', full: 'Provozovatel lokální distribuční soustavy', text: 'Provozovatel lokální distribuční soustavy' },
    { letter: 'p', term: 'PKI', full: 'Public Key Infrastructure', text: 'Technologie elektronického podpisu a šifrování (Public Key Infrastructure).' },
    { letter: 'p', term: 'Podpůrné služby', full: '', text: 'Činnosti fyzických nebo právnických osob k zajištění systémových služeb.' },
    { letter: 'p', term: 'POF', full: 'Podklady pro fakturaci', text: 'Podklady pro fakturaci' },
    { letter: 'p', term: 'POZE', full: 'Podporované zdroje energie', text: 'Podporované zdroje energie; systém podpory výroby energie z obnovitelných a druhotných zdrojů a na výrobu elektřiny z decentrálních zdrojů a z vysoce účinné kombinované výroby.' },
    { letter: 'p', term: 'PPS', full: 'Provozovatel přenosové soustavy', text: 'Provozovatel přenosové soustavy' },
    { letter: 'p', term: 'PpS', full: 'Podpůrné služby', text: 'Podpůrné služby (regulační energie)' },
    { letter: 'p', term: 'Přečerpávací vodní elektrárna', full: '', text: 'Elektrárna tvořena dvěma nádržemi v různé výšce. V době nadbytku elektřiny v síti čerpá vodu nahoru, v době nedostatku ji pouští přes turbíny dolů. V Česku je asi nejznámější elektrárna Dlouhé stráně na Jesenicku.' },
    { letter: 'p', term: 'Přenosová soustava', full: '', text: 'Jedná se o páteřní síť v ČR provozovanou společností ČEPS, a.s.' },
    { letter: 'p', term: 'Přepěťová ochrana', full: '', text: 'Chrání elektroniku před špičkami v síti.' },
    { letter: 'p', term: 'Příkon', full: '', text: 'Množství energie, které spotřebič odebere ze sítě za jednotku času. Udává se ve wattech (W). Rozdíl mezi příkonem a výkonem definuje účinnost zařízení.' },
    { letter: 'p', term: 'Přípojková skříň', full: '', text: 'Místo, kde se objekt napojuje na distribuční síť, obsahuje hlavní (zpravidla už nožové) pojistky. Někdy též nazývána jako HDS - hlavní domovní skříň.' },
    { letter: 'p', term: 'PVE', full: 'Přečerpávací vodní elektrárna', text: 'Vodní elektrárna s akumulací energie přečerpáváním vody do vyšší nádrže' },
    { letter: 'r', term: 'Reaktor', full: '', text: 'Jaderný reaktor je zařízení, ve kterém probíhá řízená štěpná řetězová reakce. Slouží k uvolňování tepelné energie z jaderného paliva.' },
    { letter: 'r', term: 'Relé', full: '', text: 'Spínací prvek, který reaguje na změnu fyzikální veličiny (proud, napětí, teplota) a ovládá další obvody. V energetice slouží také k ochraně zařízení před poruchami.' },
    { letter: 'r', term: 'Regulace frekvence', full: '', text: 'Proces udržování stabilních 50 Hz v síti vyrovnáváním výroby a spotřeby v reálném čase.' },
    { letter: 'r', term: 'Regulátor napětí', full: '', text: 'Zařízení, které udržuje výstupní napětí zdroje na konstantní úrovni bez ohledu na zatížení.' },
    { letter: 'r', term: 'Rekuperace', full: '', text: 'Proces, při kterém se část energie (např. kinetická energie brzdícího vlaku nebo teplo z ventilačního vzduchu) vrací zpět do systému k dalšímu využití.' },
    { letter: 'r', term: 'Renewables', full: '', text: 'Anglický výraz pro obnovitelné zdroje energie (OZE).' },
    { letter: 'r', term: 'Rezervovaný výkon', full: '', text: 'Maximální výkon, který může výrobce elektřiny poslat z výrobny do sítě. Sjednává se s distributorem a je pevně ukotvený ve smlouvě o připojení. Za jeho překročení hrozí ze strany distributora pokuty.' },
    { letter: 'r', term: 'Rezervovaný příkon', full: '', text: 'Hodnota hlavního jističe, kterou má zákazník pevně sjednanou s distributorem. Udává se v počtu fází a Ampérech, např. 1x20A nebo 3x25A.' },
    { letter: 'r', term: 'Rezistance', full: '', text: 'Činný elektrický odpor vodiče, ve kterém se elektrická energie mění na teplo.' },
    { letter: 'r', term: 'Rozvodna', full: '', text: 'Uzel v elektrické síti, kde se elektřina dělí do různých směrů, měří se a jistí. Často je spojena s transformovnou.' },
    { letter: 'r', term: 'Řetězová reakce', full: '', text: 'Proces, při kterém neutrony vzniklé štěpením jednoho jádra vyvolávají štěpení dalších jader. V energetice musí být tato reakce přísně řízená.' },
    { letter: 'r', term: 'Řídící tyče', full: '', text: 'Pohyblivé prvky v reaktoru obsahující pohlcovače neutronů (např. bór nebo kadmium). Jejich zasouváním nebo vysouváním se reguluje výkon reaktoru.' },
    { letter: 's', term: 'S', full: 'Siemens', text: 'Jednotka elektrické vodivosti, převrácená hodnota ohmu.' },
    { letter: 's', term: 'SCADA', full: 'Supervisory Control and Data Acquisition', text: 'Systém dispečerského řízení a sběru dat pro monitorování a ovládání technických procesů v energetice.' },
    { letter: 's', term: 'Sdílení elektřiny', full: '', text: 'Možnost sdílet vyrobenou elektřinu mezi členy skupiny sdílení nebo energetického společenství, zavedená novelou energetického zákona (Lex OZE II).' },
    { letter: 's', term: 'Sériové zapojení', full: '', text: 'Zapojení součástek, např. FVE panelů, v řadě za sebou.' },
    { letter: 's', term: 'Smart Grid', full: 'Chytrá síť', text: 'Pokročilá elektrická síť, která využívá digitální technologie k oboustranné komunikaci mezi výrobcem a spotřebitelem, čímž optimalizuje provoz a spotřebu.' },
    { letter: 's', term: 'Smart meter', full: 'Chytrý elektroměr', text: 'Digitální měřič, který v reálném čase zaznamenává spotřebu elektřiny a odesílá data distributorovi, což umožňuje například využívání dynamických tarifů.' },
    { letter: 's', term: 'Solární panel', full: '', text: 'Zařízení, které přeměňuje sluneční záření přímo na stejnosměrný elektrický proud pomocí fotoelektrického jevu.' },
    { letter: 's', term: 'Společenství pro obnovitelné zdroje', full: '', text: 'Specifický typ společenství zaměřený výhradně na zelenou energii s přísnějšími pravidly pro členství, nesmí být vytvořené za účelem zisku.' },
    { letter: 's', term: 'Spotová cena', full: '', text: 'Aktuální tržní cena elektřiny na burze.' },
    { letter: 's', term: 'Statický alokační klíč', full: '', text: 'Typ alokačního klíče s pevně stanoveným procentuálním rozdělením vyrobené elektřiny bez ohledu na aktuální spotřebu (základní varianta z Lex OZE II).' },
    { letter: 's', term: 'Střídač', full: '', text: 'Neboli invertor je klíčové zařízení, které mění stejnosměrný proud (například z fotovoltaických panelů) na střídavý, který používáme v běžných zásuvkách.' },
    { letter: 's', term: 'Svorkovnice', full: '', text: 'Místo pro spojení více vodičů.' },
    { letter: 's', term: 'SVR', full: 'Služby výkonové rovnováhy', text: 'Služby zajišťující rovnováhu mezi výrobou a spotřebou elektřiny v elektrizační soustavě, poskytované ČEPS.' },
    { letter: 't', term: 'Tarif', full: '', text: 'Vysoký nebo nízký, v nízkém tarifu jsou nižší ceny obchodníka i distributora. Dříve známý jako "noční proud", přepínání mezi vysokým a nízkým tarifem funguje pomocí HDO.' },
    { letter: 't', term: 'Tepelné čerpadlo', full: '', text: 'Zařízení, které odčerpává teplo z okolí (země, voda, vzduch) a pomocí elektrické práce ho převádí na vyšší teplotní hladinu pro vytápění.' },
    { letter: 't', term: 'Tepelná elektrárna', full: '', text: 'Zařízení vyrábějící elektřinu přeměnou tepelné energie získané spalováním paliva na mechanickou a následně elektrickou.' },
    { letter: 't', term: 'Technická flexibilita', full: '', text: 'Schopnost technologií a zařízení rychle měnit výkon nebo spotřebu. Je klíčová pro stabilitu sítě.' },
    { letter: 't', term: 'Transformátor', full: '', text: 'Přístroj umožňující měnit napětí, aby se minimalizovaly ztráty v kabelech.' },
    { letter: 't', term: 'Transformovna', full: '', text: 'Objekt v přenosové soustavě osazený transformátory, kde se mění napěťová hladina.' },
    { letter: 't', term: 'Třífázová soustava', full: '', text: 'Systém tří střídavých proudů posunutých o 120°.' },
    { letter: 't', term: 'Turbína', full: '', text: 'Točivý stroj, který přeměňuje kinetickou nebo tepelnou energii proudící látky (voda, pára, vzduch) na mechanickou energii hřídele.' },
    { letter: 'u', term: 'Uran', full: '', text: 'Těžký kov, jehož izotop 235U je základním palivem pro jaderné elektrárny díky své schopnosti udržet štěpnou řetězovou reakci.' },
    { letter: 'u', term: 'Ukládání energie', full: '', text: 'Proces uchování přebytečné energie pro pozdější využití, např. v bateriích nebo přečerpávacích vodních elektrárnách.' },
    { letter: 'u', term: 'Uzemnění', full: '', text: 'Vodivé spojení elektrického obvodu nebo zařízení se zemí pro zajištění ochrany před úrazem elektrickým proudem a správnou funkci ochran.' },
    { letter: 'u', term: 'Usměrňovač', full: '', text: 'Elektrotechnické zařízení, např. diodový můstek, který mění střídavý proud na stejnosměrný.' },
    { letter: 'u', term: 'Uhlíková stopa', full: '', text: 'Množství emisí skleníkových plynů, které vznikne při výrobě energie nebo provozu zařízení po celou dobu jeho životnosti.' },
    { letter: 'u', term: 'Udržitelnost', full: '', text: 'Schopnost energetického systému fungovat dlouhodobě bez vyčerpání přírodních zdrojů a bez nevratného poškození životního prostředí.' },
    { letter: 'ú', term: 'Úložiště energie', full: '', text: 'Zařízení pro akumulaci elektřiny (např. bateriová úložiště); samostatná úložiště podporována od října 2025 díky Lex OZE III.' },
    { letter: 'v', term: 'Vodní elektrárna', full: '', text: 'Energetické dílo využívající energii proudící nebo padající vody pohonu turbíny.' },
    { letter: 'v', term: 'Větrná elektrárna', full: '', text: 'Elektrárna využívající energii větru k roztočení rotoru, jenž následně přes generátor vyrobí elektřinu.' },
    { letter: 'v', term: 'Vysoké napětí', full: '', text: 'Napěťová hladina (v ČR od 1 kV do 52 kV), která slouží k distribuci elektřiny na střední vzdálenosti.' },
    { letter: 'v', term: 'Výměník tepla', full: '', text: 'Zařízení, ve kterém dochází k předávání tepelné energie mezi dvěma médii (např. voda-voda, spaliny-voda), aniž by se tato média promíchala.' },
    { letter: 'v', term: 'Vlastní spotřeba', full: '', text: 'Množství energie, kterou elektrárna sama spotřebuje na svůj provoz (čerpadla, řízení, osvětlení...) než pošle zbytek do sítě.' },
    { letter: 'v', term: 'Virtuální baterie', full: '', text: 'Služba dodavatele, který si "uloží" přebytky z výrobny do sítě a později je vrátí (obvykle pouze za poplatek za distribuci).' },
    { letter: 'v', term: 'V2G', full: 'Vehicle-to-grid', text: 'Využití baterie auta pro napájení sítě, něco jako "zpětný chod".' },
    { letter: 'v', term: 'V', full: 'Volt', text: 'Jednotka elektrického napětí' },
    { letter: 'v', term: 'VA', full: 'Voltampér', text: 'Jednotka zdánlivého výkonu v AC soustavách' },
    { letter: 'v', term: 'Var', full: 'Voltampér reaktanční', text: 'Jednotka jalového výkonu v AC soustavách' },
    { letter: 'v', term: 'VVN', full: 'Velmi vysoké napětí', text: 'Používá se k distribuci elektřiny na větší vzdálenosti v rozsahu 52 - 300 kV.' },
    { letter: 'w', term: 'W', full: 'Watt', text: 'Jednotka činného elektrického výkonu' },
    { letter: 'w', term: 'Wh', full: 'Watthodina', text: 'Jednotka elektrické energie odpovídající výkonu 1 W po dobu 1 hodiny.' },
    { letter: 'w', term: 'Wallbox', full: '', text: 'Domácí nabíječka pro elektromobily.' },
    { letter: 'w', term: 'Wattmetr', full: '', text: 'Přístroj určený k přímému měření činného elektrického výkonu v obvodech stejnosměrného i střídavého proudu.' },
    { letter: 'w', term: 'Wattpeak', full: '', text: 'Jednotka jmenovitého špičkového výkonu udávající, kolik energie panel vyrobí v ideálních podmínkách.' },
    { letter: 'z', term: 'Zatížení sítě', full: '', text: 'Okamžitý odběr elektřiny všemi spotřebiči připojenými v síti. Energetici musí neustále hlídat, aby výroba přesně odpovídala tomuto zatížení.' },
    { letter: 'z', term: 'Záložní zdroj', full: '', text: 'Zařízení, které dodává energie v případě výpadku hlavní sítě (např. dieselagregát nebo bateriové úložiště).' },
    { letter: 'z', term: 'Zbytkové teplo', full: '', text: 'Teplo, které vzniká jako vedlejší produkt při výrobě elektřiny nebo v průmyslu a které lze dále využít, např. pro dálkové vytápění měst.' },
    { letter: 'z', term: 'Zdroj energie', full: '', text: 'Souhrnné označení pro jakýkoliv zdroj nebo surovinu, ze které lze získat užitečnou energii (slunce, vítr, uhlí, jádro).' },
    { letter: 'z', term: 'Zemnicí soustava', full: '', text: 'Síť vodičů a zemničů v zemi, která zajišťuje, aby nežádoucí proudy (např. při úderu blesku nebo poruše) bezpečně odešly do země.' },
    { letter: 'z', term: 'Zkrat', full: '', text: 'Nežádoucí vodivé spojení dvě fází nebo fáze a země, při kterém protéká obvodem extrémně vysoký proud. Systém se v takovém případě musí okamžitě odpojit jističem.' }
];

// Statistiky pro ladění

console.log(`Slovník načten: ${window.TERMS.length} pojmů`);
